Remove extra ';' in table_of_recent_compares.h
The patch
https://github.com/google/fuzztest/commit/8b93bbe62eb356e8555e44d3f1c2f418783e3adb
introduced an extra ';' two weeks ago.

This causes chromium fuzztest autoroller to fail at the moment:
```
fuzztest/internal/table_of_recent_compares.h:219:79: error: extra ';' after member function definition [-Werror,-Wextra-semi]
  219 |   explicit TableOfRecentlyComparedBuffers(bool compact) : compact_(compact) {};
```

Bug: https://github.com/google/fuzztest/issues/1857
Bug: https://issues.chromium.org/issues/444348065
Fixed: https://github.com/google/fuzztest/issues/1857
Fixed: https://issues.chromium.org/issues/444348065